// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPX7quKDQe1rGt2Tzm0zi7GiHDgRcauvA',
    appId: '1:1057761954918:web:95114763e6474f7392b1a7',
    messagingSenderId: '1057761954918',
    projectId: 'f-event-app',
    authDomain: 'f-event-app.firebaseapp.com',
    storageBucket: 'f-event-app.firebasestorage.app',
    measurementId: 'G-X8LTZ67QBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbOAO2HhC-hopqQj9fKzU1qn4cVF3VyBY',
    appId: '1:1057761954918:android:64daca6daca732a792b1a7',
    messagingSenderId: '1057761954918',
    projectId: 'f-event-app',
    storageBucket: 'f-event-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNI0yFOvKlEYzBeRe5NSuCURw57qZfks',
    appId: '1:1057761954918:ios:be0b617a9b677e8692b1a7',
    messagingSenderId: '1057761954918',
    projectId: 'f-event-app',
    storageBucket: 'f-event-app.firebasestorage.app',
    iosBundleId: 'com.communityevents.app',
  );
}
